[project]
name = "pyntcloud-implementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plyfile>=1.1.3",
    "pyntcloud>=0.3.1",
]
